sudo: false
language: node_js
node_js:
    - 6
    - 5
    - 4
    - 0.12
    - 0.10
script:
    - npm test
    - npm run lint
addons:
  code_climate:
    repo_token: sa
after_success: npm run coverage